apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  labels:
    app: swath
  namespace: swath
  name: swath-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: swath.gule-gulzar.com
    http:
      paths:
      - backend:
          service:
            name: swath-lb
            port:
              number: 80
        pathType: exact